# Generated by Django 3.0 on 2020-09-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passward',
            field=models.CharField(max_length=32),
        ),
    ]
